python3.5 query_biomart.py -i ATA_12_Hard-Clipping.pos.txt
sleep 240; echo "14 ----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_14_Hard-Clipping.pos.txt
sleep 240; echo "15-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_15_Hard-Clipping.pos.txt
sleep 240; echo "19-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_19_Hard-Clipping.pos.txt
sleep 240; echo "1------------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_1_Hard-Clipping.pos.txt
sleep 240; echo "20-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_20_Hard-Clipping.pos.txt
sleep 240; echo "21-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_21_Hard-Clipping.pos.txt
sleep 240; echo "22-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_22_Hard-Clipping.pos.txt
sleep 240; echo "23-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_23_Hard-Clipping.pos.txt
sleep 240; echo "24-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_24_Hard-Clipping.pos.txt
sleep 240; echo "25-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_25_Hard-Clipping.pos.txt
sleep 240; echo "27-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_27_Hard-Clipping.pos.txt
sleep 240; echo "28-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_28_Hard-Clipping.pos.txt
sleep 240; echo "2-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_2_Hard-Clipping.pos.txt
sleep 240; echo "31-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_31_Hard-Clipping.pos.txt
sleep 240; echo "32-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_32_Hard-Clipping.pos.txt
sleep 240; echo "3-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_3_Hard-Clipping.pos.txt
sleep 240; echo "4-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_4_Hard-Clipping.pos.txt
sleep 240; echo "5-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_5_Hard-Clipping.pos.txt
sleep 240; echo "6-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_6_Hard-Clipping.pos.txt
sleep 240; echo "7-----------------------------------------------------------------------------------"
python3.5 query_biomart.py -i ATA_7_Hard-Clipping.pos.txt
