---
title: "Plotting_GNAS_Gviz"
author: "Monzó, Carolina"
date: "5/11/2018"
output: pdf_document
---

```{r, warning=FALSE, message=FALSE}
library(data.table)
library(Gviz)
library(GenomicFeatures)
library(IRanges)
```

```{r, plotting}
## PLOTTING GNAS
atrack = UcscTrack(track="CpG Islands", chromosome="chr20", genome="hg19",
                    start="chromStart", end="chromEnd", name="CpG Islands",
                   from=57225763, to=57486250)

itrack = IdeogramTrack(genome = "hg19", chromosome = "chr20")

grtrack = UcscTrack(genome = "hg19", chromosome = "chr20", track = "ensGene",
                    from = 57225763, to = 57486250, trackType = "GeneRegionTrack", 
                    rstarts = "exonStarts", rends = "exonEnds", gene = "name", 
                    symbol = "name2", transcript = "name", strand = "strand", 
                    name = "GNAS complex locus", stacking = "pack")

regionsOfInterest = IRanges(start = c(57225763, 57264187, 57414795), 
                            end = c(57254582, 57291367, 57486250))
names(regionsOfInterest) = c("STX16", "NPEPL1", "GNAS")

gtrack = GenomeAxisTrack(range = regionsOfInterest, showId = TRUE, add53=T, add35=T)

plotTracks(list(itrack, gtrack, atrack, grtrack), 
           from = 57225763, to = 57486250,
           sizes = c(0.1, 0.15, 0.10, 0.50))
```

