---
title: "Untitled"
author: "asj"
date: "10/15/2014"
output: html_document
---

##Required libraries
```{r}
library("xlsx")
library("ggplot2")
```

##Working directory
```{r}
wd <- "/cpd_home/asj/production/plots/ggplot/hypobeta_20141015"

plots_dir <- file.path(wd, "plots")
analysis_dir <- file.path(wd, "analysis")
```

##Getting data from winbioinfo
```{r}
cov_file_path <- "/home/asj/winbioinfo/projects_results/UGDG/hypobeta/results/summaries/hypobeta_summary-20141015.xlsx"
mean_coverage_data <- read.xlsx(cov_file_path, sheetIndex = 1)
coverage_percent_data <- read.xlsx(cov_file_path, sheetIndex = 2)

# values_colours

```

##Ggplot
```{r}
plot_path <- file.path(plots_dir, "percent_coverage_by_depth.png")

# png(file=plot_path)

    p <- ggplot(coverage_percent_data, aes(x=depth, y=percent, group=sample, colour = sample))
     
    p + geom_line(size=1) + geom_point() +
      scale_y_continuous(limits=c(0, 100)) +
      scale_x_continuous(breaks=seq(5,30,5), labels=paste0(seq(5,30,5), "X")) +
    #   scale_color_manual(values=c("red", "blue", "green", "black")) +
      ggtitle(paste0("% Coverage by depth")) + 
      xlab("Depth") + ylab("Percentage bases covered") + 
      theme(plot.title=element_text(size=28, lineheight=.8, face="bold")
      , axis.text=element_text(size=18)
      , axis.title=element_text(size=16)
#       , axis.text.x=element_text(angle=90, vjust=0.5)
      , legend.position = "none"
      )
 

# dev.off()
```
